// File generated by AI Studio Build.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_signatures
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4dutrdz81MZ2ykfQExTR1rnfn3iH7ZOo',
    appId: '1:129694048718:web:f181e3326bc2d4d3a64b9f',
    messagingSenderId: '129694048718',
    projectId: 'besheger-apps',
    authDomain: 'besheger-apps.firebaseapp.com',
    storageBucket: 'besheger-apps.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4dutrdz81MZ2ykfQExTR1rnfn3iH7ZOo',
    appId: '1:129694048718:web:f181e3326bc2d4d3a64b9f', // Using web appId as placeholder for mobile
    messagingSenderId: '129694048718',
    projectId: 'besheger-apps',
    storageBucket: 'besheger-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4dutrdz81MZ2ykfQExTR1rnfn3iH7ZOo',
    appId: '1:129694048718:web:f181e3326bc2d4d3a64b9f', // Using web appId as placeholder for mobile
    messagingSenderId: '129694048718',
    projectId: 'besheger-apps',
    storageBucket: 'besheger-apps.firebasestorage.app',
    iosBundleId: 'com.example.gojoMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4dutrdz81MZ2ykfQExTR1rnfn3iH7ZOo',
    appId: '1:129694048718:web:f181e3326bc2d4d3a64b9f', // Using web appId as placeholder for mobile
    messagingSenderId: '129694048718',
    projectId: 'besheger-apps',
    storageBucket: 'besheger-apps.firebasestorage.app',
    iosBundleId: 'com.example.gojoMarketplace',
  );

  static const String firestoreDatabaseId = 'ai-studio-62c8bd19-b811-4395-8222-f2982fdc90dd';
}
